services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: secure-cloud-web

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    command: python manage.py runserver 0.0.0.0:8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker

    container_name: secure-cloud-worker

    env_file:
      - .env

    volumes:
      - .:/app

    command: python worker/worker.py

    depends_on:
      - web